language: php

matrix:
  include:
    - php: 7.4
      before_install: composer require --dev phpunit/phpunit ^9
      script: ./vendor/bin/phpunit --version
    - php: 7.3
      before_install: composer require --dev phpunit/phpunit ^9
      script: ./vendor/bin/phpunit --version
    - php: 7.2
      before_install: composer require --dev phpunit/phpunit ^8
      script: ./vendor/bin/phpunit --version
    - php: 7.1
      before_install: composer require --dev phpunit/phpunit ^7
      script: ./vendor/bin/phpunit --version
    - php: 7.0
      before_install: composer require --dev phpunit/phpunit ^6
      script: ./vendor/bin/phpunit --version
    - php: 5.6
      before_install: composer require --dev phpunit/phpunit ^5
      script: ./vendor/bin/phpunit --version
    - php: 5.5
      dist: trusty
      before_install: composer require --dev phpunit/phpunit ^4
      script: ./vendor/bin/phpunit --version
    - php: 5.4
      dist: trusty
      before_install: composer require --dev phpunit/phpunit ^4
      script: ./vendor/bin/phpunit --version
    - php: 5.3
      dist: precise
      before_install: composer require --dev phpunit/phpunit ^4
      script: ./vendor/bin/phpunit --version
    - php: hhvm
      dist: trusty
      script: phpunit --version
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --no-progress --no-ansi
